task(readme): Certificate installation instructions on iOS and Android
ForgeRock/forgerock-react-native-sample pull request #13
Opened 2021-10-26 20:38 UTC by ryanbas21

should describe the steps to generate a root certificate and install a
signed certificate on the local server

https://bugster.forgerock.org/jira/browse/SDKS-1213

2021-11-02 18:03 UTC, cerebrl requested changes

2021-11-02 18:03 UTC, cerebrl commented on README.md
> +#### Styling and CSS
Should probably remove CSS as I believe it's not relevant for mobile.

2021-11-02 18:03 UTC, cerebrl commented on README.md
> +Now, you should be able to visit `https://react.example.com:8443`, which is your web app or client (the Relying Party in OAuth terms). This client will make requests to your AM instance, (the Authori
This should be modified to suit React Native.

2021-11-02 18:03 UTC, cerebrl commented on README.md
> +This project contains comments describing the SDK integration points. We utilize both, the `iOS` bridge code and the Javascript SDK. Please see the comments in the source code to follow along with th
Please remove this.

2021-11-02 18:03 UTC, cerebrl commented on README.md
> +2. Make sure you have a `.env` file with valid values.
This should be changed to `.env.js`.

2021-11-02 18:03 UTC, cerebrl commented on README.md
> +```
We should mention `pod install` as well

2021-11-02 22:37 UTC, cerebrl commented on docs/ios-certificates.md
> +  - Add the generated certificate files as the serving SSL certificate in your server. For this app, populate the .env file with the appropriate values
We should updated this to reflect the new `.env.js` file, yeah?

2021-11-03 14:07 UTC, cerebrl requested changes

2021-11-03 18:53 UTC, cerebrl approved these changes

2021-11-03 19:47 UTC, spetrov approved these changes
Looks good to me. 👍🏻 
Pretty straightforward and easy to follow.

2021-11-04 01:59 UTC, merged