feature(remove-env): Using Env not needed for react-native
ForgeRock/forgerock-react-native-sample pull request #15
Opened 2021-10-26 22:06 UTC by ryanbas21

Due to the complexity of adding a certificate on mobile, along with the
difficulties of using env files in react native (caching issues) we do
not need an env file for the react native portion. We also may not need
an env file at all if we go with a hosted server and have the user edit
the plist file directly.

https://bugster.forgerock.org/jira/browse/SDKS-1213

2021-11-01 16:31 UTC, cerebrl commented on reactnative-todo/src/components/utilities/request.js
> +    const res = await fetch(`https://api.example.com:9443/todos/${resource}`, {
Do we have a `constants` file or a better place to put such a value. I'm afraid this is a bit hidden. Also, I'd like to have a check when the app boots up to check if a value is present, if not, it errors.

2021-11-01 16:36 UTC, cerebrl requested changes
What if we created a `.env.js` file, rather than a `.env` file? We could move all values over to it. `gitignore` the `.env.js` file but have a `.env.js.example` that isn't ignored that they use as a template.

2021-11-01 16:57 UTC, daveadams56 commented
I agree with Justin about moving the API URL to a .js file within the project. If there is a .env file setup within the project for the backend, perhaps a step in the build that could read .env and inject into a config file within the react native project could reduce duplication? An example where I've done this for the Angular sample app is here: [set-env.mjs](https://github.com/daveadams56/angular-todo-prototype/blob/main/set-env.mjs)

2021-11-01 19:40 UTC, cerebrl commented on reactnative-todo/.env.example.js
> +const API_URL = ''
Could we just move all of the variables from `.env`, even those related to the Node.js server needs?

2021-11-02 02:39 UTC, cerebrl commented on README.md
> +9. Create the `.env.mjs` file from the `.env.example.js` file
This should be `.env.js`, yeah?

2021-11-02 02:45 UTC, cerebrl approved these changes
Other than the small typo, this looks good.

2021-11-02 15:33 UTC, daveadams56 commented
Looks good to me

2021-11-02 16:24 UTC, merged